//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.MusicStreamingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Music", Namespace="http://schemas.datacontract.org/2004/07/WCFMusicStreamingServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class Music : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlbumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArtistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AvaiableToStreamingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Album {
            get {
                return this.AlbumField;
            }
            set {
                if ((object.ReferenceEquals(this.AlbumField, value) != true)) {
                    this.AlbumField = value;
                    this.RaisePropertyChanged("Album");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Artist {
            get {
                return this.ArtistField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistField, value) != true)) {
                    this.ArtistField = value;
                    this.RaisePropertyChanged("Artist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AvaiableToStreaming {
            get {
                return this.AvaiableToStreamingField;
            }
            set {
                if ((this.AvaiableToStreamingField.Equals(value) != true)) {
                    this.AvaiableToStreamingField = value;
                    this.RaisePropertyChanged("AvaiableToStreaming");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Time {
            get {
                return this.TimeField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeField, value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmptyQueueException", Namespace="http://schemas.datacontract.org/2004/07/WCFMusicStreaming.Model.Exception")]
    [System.SerializableAttribute()]
    public partial class EmptyQueueException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MusicStreamingService.IMusicStreaming")]
    public interface IMusicStreaming {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusicStreaming/StreamMusic", ReplyAction="http://tempuri.org/IMusicStreaming/StreamMusicResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Client.MusicStreamingService.EmptyQueueException), Action="http://tempuri.org/IMusicStreaming/StreamMusicEmptyQueueExceptionFault", Name="EmptyQueueException", Namespace="http://schemas.datacontract.org/2004/07/WCFMusicStreaming.Model.Exception")]
        Client.MusicStreamingService.Music StreamMusic();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusicStreaming/StreamMusic", ReplyAction="http://tempuri.org/IMusicStreaming/StreamMusicResponse")]
        System.Threading.Tasks.Task<Client.MusicStreamingService.Music> StreamMusicAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusicStreaming/GetAvaiableMusics", ReplyAction="http://tempuri.org/IMusicStreaming/GetAvaiableMusicsResponse")]
        Client.MusicStreamingService.Music[] GetAvaiableMusics();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMusicStreaming/GetAvaiableMusics", ReplyAction="http://tempuri.org/IMusicStreaming/GetAvaiableMusicsResponse")]
        System.Threading.Tasks.Task<Client.MusicStreamingService.Music[]> GetAvaiableMusicsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMusicStreamingChannel : Client.MusicStreamingService.IMusicStreaming, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MusicStreamingClient : System.ServiceModel.ClientBase<Client.MusicStreamingService.IMusicStreaming>, Client.MusicStreamingService.IMusicStreaming {
        
        public MusicStreamingClient() {
        }
        
        public MusicStreamingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MusicStreamingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MusicStreamingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MusicStreamingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.MusicStreamingService.Music StreamMusic() {
            return base.Channel.StreamMusic();
        }
        
        public System.Threading.Tasks.Task<Client.MusicStreamingService.Music> StreamMusicAsync() {
            return base.Channel.StreamMusicAsync();
        }
        
        public Client.MusicStreamingService.Music[] GetAvaiableMusics() {
            return base.Channel.GetAvaiableMusics();
        }
        
        public System.Threading.Tasks.Task<Client.MusicStreamingService.Music[]> GetAvaiableMusicsAsync() {
            return base.Channel.GetAvaiableMusicsAsync();
        }
    }
}
